### ISSUE TITLE
你好，请问如何制作自己的xxx.db文件？

### ISSUE THREAD

**Issue by liudonglei** [AprilGroup/DrQA-CN#1]
请问作者制作自己的MBA.db时，用到了哪些.py文件来转换的？

**Comment by 731935354** [comment]
首先创建形如
{"id": "doc1", "text": "text of doc1"}
...
{"id": "docN", "text": "text of docN"}
的json文件，然后调用scripts/retriever/build_db.py
python build_db.py /path/to/data /path/to/saved/db.db

**Comment by liudonglei** [comment]
好的，谢谢，我会试试。
