### ISSUE TITLE
您好，请问数据集能提供一下吗

### ISSUE THREAD

**Issue by mooe1011** [AprilGroup/DrQA-CN#3]
如题，谢谢

**Comment by 731935354** [comment]
不好意思啊这个数据集是当时实习的时候公司提供的，现在已经拿不到了。------------------ 原始邮件 ------------------
发件人: "mooe1011"<notifications@github.com>
发送时间: 2020年3月13日(星期五) 上午9:39
收件人: "AprilGroup/DrQA-CN"<DrQA-CN@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [AprilGroup/DrQA-CN] 您好，请问数据集能提供一下吗 (#3)

**Comment by mooe1011** [comment]
好的，谢谢
